module FictionalMorpheme_en exposing (fictionalMorphemeData_en)
fictionalMorphemeData_en = """
?all = Noun:?all-noun Verb:@conjugated-verb Adjective:?all-adjective Adverb:?all-adverb Pronoun:?pronoun Preposition:?all-preposition Conjunction:?all-conjunction Determiner:?all-determiner
?all-adjective = ActiveVerb:?verb PassiveVerb:?verb NounAsAdjective:?all-noun PronounAsAdjective:?pronoun
?all-noun = AllConcept:?concept AllWord:?basic-word Math:?math-noun Content:?content-noun Science:?science-noun
?all-adverb = Core:$core-adverb Frequency:$frequency-adverb Probability:$probability-adverb Completion:$completion-adverb Time:$time-adverb
?all-preposition = Core:$core-preposition
?all-conjunction = Set:$set-conjunction Condition:$condition-conjunction TimeSpace:$time-space-conjunction
?all-determiner = Core:$core-determiner Distributive:$distributive-determiner Quantifier:$quantifier-determiner Position:$about-these Specific:$specific-this Fract11:$eleventh
?basic-word= Creature:@creature Building:@building KnownSeries:?known-series
?building-characteristic = BigHeightBuilding:@big-unit NumberOfRooms:@big-unit
?concept = GeneralConcept:$general-concept Organic:$nature-type Landscape:$terrain Color:$color-spectrum Sentiment:$sentiment-options Sensation:?sensation-options Transport:@transportation
?creature-characteristic = SmallWeightCreature:@small-unit BigWeightCreature:@big-unit SmallHeightCreature:@small-unit BigHeightCreature:@big-unit SmallLengthCreature:@small-unit BigLengthCreature:@big-unit CreatureDna:@big-unit
?known-series = Mendeleev:@to-100 Status:@to-1000 Unicode:@to-unicode Fibonacci:@integers-
?movement-direction = LinearMovement:$base12 Accelerating:$base12 Decelerating:$base12 EaseInOut:$base12
?movement= TwoPoses:@seq2-pose ThreePoses:@seq3-pose
?nominated = EntityOfName:@entity-name GroupOfName:@group-of-name ThisEntity:@consonant10s- ThisGroup:@consonant10s-
?pose = UpperPose:@two-arms LowerPose:@two-legs HeadPose:@head BodyPose:@arms-legs HandPose:@fingers
?pronoun = JustI You YouAndI IAnd:@consonant10s- Them:@consonant10s-
?sensation-options = Balance Hunger Hearing Pain Sight Smell Taste Touch SexualStimulation TemperatureSense ColorSensing:$color-spectrum BasicElementSensing:$basic-elements
?verb = ActionOf:@action-of
?math-noun = Unit:$unit-noun Trigo:$trigo-noun Polygon:$polygon-noun Shape:$shape-noun AsType:$as-type-noun Number:$number-sequence-noun Direction:$direction-noun Pattern:$pattern-action
?content-noun = Visual:$visual-noun Text:$text-noun VisualArt:$visual-art-noun Rights:$rights-noun FactChecking:$fact-checking
?science-noun = Electric:$electric-noun Chemistry:$chemistry-terms ChemistryComponent:$chemistry-component-noun Physics:$physics UniverseBig:$universe-big UniverseSmall:$universe-component History:$history Geo:$geography Society:$society
@action-of= Management:$management Adverb:$core-adverb Concept:?concept
@arm = ShoulderRotationSide:$base12 ShoulderRotationFront:$base12 ElbowRotation:$base12
@arms-legs = Arms:@two-arms Legs:@two-legs
@big-unit = Prefix:$big-unit-prefix Value:$unit-value
@building = Domain:$god-domain Characteristic:?building-characteristic
@conjugated-verb = Tense:$tense Verb:?verb
@consonant10s- = Consonant:$consonant10
@creature= NatureType:$nature-type Terrain:$terrain Characteristic1:?creature-characteristic Characteristic2:?creature-characteristic
@entity-name = Type:$nominated-type Sound:@consonant10s-
@fingers = Thumb:$base12 IndexFinger:$base12 MiddleFinger:$base12 RingFinger:$base12 LittleFinger:$base12
@group-of-name = GroupType:$nominated-group-type Sound:@consonant10s-
@head = HeadRotationSide:$base12 HeadRotationFront:$base12
@integers- = Base10:$base10
@leg = LegRotationSide:$base12 LegRotationFront:$base12 KneeRotation:$base12
@seq2-pose = Pose1:?pose Movement:?movement-direction Pose2:?pose
@seq3-pose = Pose1:?pose Movement1:?movement-direction Pose2:?pose Movement2:?movement-direction Pose3:?pose
@small-unit = Prefix:$small-unit-prefix Value:$unit-value
@to-100 = Tens:$base10 Units:$base10
@to-1000 = Hundreds:$base10 Tens:$base10 Units:$base10
@to-unicode = Uni1:$base10 Uni2:$base10 Uni3:$base10 Uni4:$base10 Uni5:$base10 Uni6:$base10
@transportation = Element:$basic-elements Prefix:$big-unit-prefix Value:$unit-value
@two-arms = LeftArm:@arm RightArm:@arm
@two-legs = LeftLeg:@leg RightLeg:@leg
$about-these = FirstOfThese NextOfThese PreviousOfThese LastOfThese OtherOfThese
$base10 = Zero10 One10 Two10 Three10 Four10 Five10 Six10 Seven10 Eight10 Nine10 Dot10 Eon10
$base12 = Zero12 One12 Two12 Three12 Four12 Five12 Six12 Seven12 Eight12 Nine12 Ten12 Eleven12
$basic-elements = Earth Water Air Fire Void Time Ice Biological Magic Dream EnergyField
$big-unit-prefix = BigUnit Kilo Mega Giga Tera Peta Exa Zetta Yotta
$color-spectrum = Black Infrared Red Orange Yellow Green Cyan Blue Violet NearUltraviolet FarUltraviolet White
$comparator = Equal NotEqual ApproximatelyEqual SameOrderOfMagnitude GreaterThan LessThan IsOfGreaterOrderThan IsOfSmallerOrderThan
$consonant10 = LP LT LK LM LN LD LB LG LW LJ EOC10
$core-adverb = Carefully Carelessly Slowly Fastly Perfectly Imperfectly EfficientLy Inefficiently Fortunately Unfortunately Briefly Endlessly
$final-state = Empty Full
$general-concept = AnyBuilding AnyColor AnyFood AnyLandscape AnyOrganic AnySensation AnySentiment AnyTransport Belief Money Person Place
$god-domain = Arts Chaos Commerce Health Housing Justice Knowledge Messenger Nature Scheduling Smithing War
$management = Append Clear Compose Decompose Extract Inspect Measure Refine Remove Sort Transform Watch
$musical-note = Do DoDiesis Re ReDiesis Mi Fa FaDiesis Sol SolDiesis La LaDiesis Si
$nature-type = Amphibian Annelid Arthropod Bird Echinoderm Fish Insect Mammal Mollusc Plant Reptile Spider
$nominated-group-type = Country City
$nominated-type = Human Robot
$sentiment-options = Afraid Angry Annoyed Bored Charmed Desire Dissatisfied Happy Jealous Mad Sad Surprised
$small-unit-prefix = SmallUnit Milli Micro Nano Pico Femto Atto Zepto Yocto
$tense = FarPast Past Present Future FarFuture Hypothesis Request Promise Attempt Prediction Warning Fantasy
$terrain = Canyon Desert Forest Hill Mountain Oasis Ocean Openground Plain River Swamp Valley
$terrain-extra = Archipelago Bay Cave Cliff Dune Estuary Geyser Glacier Gulf Island Lake Volcano
$unit-value = Around0 LessThan1 LessThan2 LessThan4 LessThan8 LessThan16 LessThan32 LessThan64 LessThan128 LessThan256 LessThan512 LessThan1024
$core-preposition = Of With At From Into During Including Till Against Among Throughout Despite
$set-conjunction = Or And Nor NotAnd ExclusiveOr Except Unless Whether
$time-space-conjunction = When While Where Before After Since Until Once
$condition-conjunction = If Because But Although As Therefore
$core-determiner = Indefinite Definite Demonstrative Possessive Other Another
$distributive-determiner = All Both Half Either Neither Each Every
$quantifier-determiner = Few Much Many Most Some Any Enough
$frequency-adverb = Never Rarely Sometimes Regularly Often Always
$probability-adverb = Unlikely Perhaps Possibly Probably Likely Certainly
$completion-adverb = Hardly Somewhat Mediocrely Nearly Roughly Fully Exceedingly
$time-adverb = Anciently Recently Immediately Currently Soon Eventually Ultimately
$rights-noun = Adaptation Appropriation Artifice Attribution Brand Censorship Commercial Culture Licence Propaganda Rights
$classified-adjective = Public OpenAccess Clearance Unclassified Official Restricted Confidential Secret TopSecret ClosedAccess Private
$visual-noun = Background Canvas Composition Contour Foreground MiddleGround Motif Palette Style
$text-noun = Char Word CompoundWord LineOfText Sentence Paragraph TextDocument TextBook TextLibrary Font
$visual-art-noun = Drawing Painting Architecture
$answer-adjective = Incorrect Correct Unknown Known Difficult Easy Unreasonable Reasonable Unbelievable Believable Inaccurate Accurate
$operator-verb = Add Ceiling Divide Exponentiation Floor Invert Modulo Multiply Round SignChange Subtract
$player-verb = Play Rewind FastForward Pause Reverse Stop SkipPrevious SkipNext RepeatForever RepeatOnce Replay
$spinner-verb = Increase Decrease ZoomIn ZoomOut
$boolean-verb = Hide Show
$building-function-noun = Archive Castle Factory Hospital House Market Park Port Prison School Temple Warehouse
$building-link-noun = Bridge Canal Gateway Nexus Road Skyway Spaceway Tunnel
$unit-noun = Angle Area Density Energy Force Frequency Length Mass Pressure Temperature Time Volume
$trigo-noun = Arccosine Arcsine Arctangent Cosine EulerNumber Factorial GoldenRatio Pi Sine SquareRoot SquareRootOf2 Tangent
$polygon-noun = Dot Line Triangle Quadrilateral Pentagon Hexagon Heptagon Octagon Nonagon Decagon Hendecagon Dodecagon
$shape-noun = Annulus Circle Crescent Ellipse Fractal Lens Polygon Polyline Spiral Star StarPolygon VisualPath
$as-type-noun = Boolean ComplexNumber Integer NaturalNumber RationalNumber RealNumber
$number-sequence-noun = AlgebraicNumbers ComputableNumbers ConstructibleNumbers EvenNumbers FibonacciNumbers IrrationalNumbers OddNumbers PerfectNumbers PrimeNumbers TranscendentalNumbers NegativeInfinity Infinity
$direction-noun = Backward BackwardLeft BackwardRight Forward ForwardLeft ForwardRight Left Right
$list-select-verb = Drop Filter Find First Last MemberOf Omit Pick Reject Rest Sample
$list-org-verb = Flatten Partition Range Reverse Shuffle Sort
$list-stats-verb = AllSatisfies AnySatisfies Count IsEmpty Max Mean Min ReduceFromLeft ReduceFromRight Sum
$list-add-verb = AddLeft AddRight Append
$electric-noun = Charge Circuit Conductor Current Field Generator Insulator Magnet Motor Resistance
$chemistry-terms = Abundance Accuracy Catalyst ChainReaction Concentration Density Distillation Entropy Equilibrium Indicator Polarity Solution
$chemistry-verb = Burn Compress Condense Corrode Diffuse Disperse Dissolve Extract Freeze Melt
$chemistry-component-noun = Acid Alcohol Alloy Compound Crystal Enzyme Metal Mineral Mineral Rust Salt Solvent
$severity-level-verb = Emergency Alert Critical Error Warning Notice Informational Debug Console
$physics = Acceleration Adhesion Elasticity Fluid Friction Fusion Gravity Ground Heat Inertia Motion Power
$physics-verb = Bend Collide Deflect Deform Drag Emit Focus Radiate Scatter Stress
$other = Split Trajectory Speed Vacuum Viscosity Sound Wave Weight Wind GeneticCode Predator Prey
$universe-big = Galaxy Multiverse Star Supernova Planet Moon Pulsar Life Light Spacehole SpaceTime Radioactivity
$universe-component = Atom Nucleus Proton Neutron Electron Element Molecule Photon Gas Matter Plasma
$eleventh = ZeroEleventh OneEleventh TwoEleventh ThreeEleventh FourEleventh FiveEleventh SixEleventh SevenEleventh EightEleventh NineEleventh TenEleventh ElevenEleventh
$blending = ZeroVsTwentyTwo OneVsTwentyOne TwoVsTwenty ThreevsNineteen FourVsEighteen FiveVsSeventeen SixVsSixteen SevenVsFifteen EightVsFourteen NineVsThirteen TenVsTwelve ElevenVsEleven
$specific-this= This ThisAction ThisAnimal ThisApproach ThisCharacteristic ThisConcept ThisContext ThisPerson ThisPlace ThisReason ThisThing ThisTimeframe
$pattern-action = SymmetryPattern SpiralPattern ChaosPattern WavePattern BubblePattern CrackPattern FractalPattern SpotStripePattern
$fact-checking = EvilSource SelfEvident EducatedSource FictionalSource AnecdotalSource VerifiedSource ReliableSource
$stress-adjective = Focus Unimportant Important Pejorative Positive Plural
$geography = Altitude Atlas
$history = Absolution Boycott Civilization Colony Confrontation Constitution Dynasty Exile Hierarchy Poll Revolution Veto
$exchange = Barter
$society = Empire Monarchy Anarchy Patriarch Republic Theocracy
$what-to-do = Fossil Myth
$war = Allies Debacle Enemy Prisoner Resistance Sacrifice Stealth Torture Trap Victory War Weapon
$battle-verb= Attack Capture Defect Defend Escape Infiltrate Intercept Spy Surrender
@disciple-of = Discipline:$god-domain
$aa = Apprentice MeleeWeapon RangedWeapon Illusion Sorcery
"""