content = {'c': {'gt': 'gt', 'gs': 'gs', 'gr': 'gr', 'gp': 'gp', 'gy': 'gy',
'gg': 'gg', 'gf': 'gf', 'gd': 'gd', 'gc': 'gc', 'gb': 'gb', 'gn': 'gn', 'gl':
'gl', 'gk': 'gk', 'ys': 'ys', 'lf': 'lf', 'lg': 'lg', 'ld': 'ld', 'yr': 'yr',
'lb': 'lb', 'lc': 'lc', 'ty': 'ty', 'ln': 'ln', 'tt': 'tt', 'tr': 'tr', 'ts':
'ts', 'tp': 'tp', 'yt': 'yt', 'tn': 'tn', 'tl': 'tl', 'lr': 'lr', 'ls': 'ls',
'lp': 'lp', 'tf': 'tf', 'tg': 'tg', 'td': 'td', 'tb': 'tb', 'tc': 'tc', 'ly':
'ly', 'dn': 'dn', 'dl': 'dl', 'dk': 'dk', 'yn': 'yn', 'df': 'df', 'dg': 'dg',
'dd': 'dd', 'yb': 'yb', 'db': 'db', 'dc': 'dc', 'yg': 'yg', 'yf': 'yf', 'yy':
'yy', 'dy': 'dy', 'yp': 'yp', 'dt': 'dt', 'cd': 'cd', 'dr': 'dr', 'ds': 'ds',
'dp': 'dp', 'rt': 'rt', 'rp': 'rp', 'rr': 'rr', 'rs': 'rs', 'ry': 'ry', 'rd':
'rd', 'rf': 'rf', 'rg': 'rg', 'rb': 'rb', 'rc': 'rc', 'rl': 'rl', 'rn': 'rn',
'rk': 'rk', 'bd': 'bd', 'bf': 'bf', 'bg': 'bg', 'bb': 'bb', 'bc': 'bc', 'bl':
'bl', 'bn': 'bn', 'bk': 'bk', 'bt': 'bt', 'bp': 'bp', 'br': 'br', 'bs': 'bs',
'by': 'by', 'll': 'll', 'ck': 'ck', 'cn': 'cn', 'cl': 'cl', 'cc': 'cc', 'cb':
'cb', 'cg': 'cg', 'cf': 'cf', 'lk': 'lk', 'cy': 'cy', 'cs': 'cs', 'cr': 'cr',
'cp': 'cp', 'ct': 'ct', 'pr': 'pr', 'ps': 'ps', 'pp': 'pp', 'pt': 'pt', 'py':
'py', 'lt': 'lt', 'pb': 'pb', 'pc': 'pc', 'pf': 'pf', 'pg': 'pg', 'pd': 'pd',
'pk': 'pk', 'pn': 'pn', 'pl': 'pl', 'tk': 'tk', 'ss': 'ss', 'yk': 'yk', 'st':
'st', 'yl': 'yl', 'sk': 'sk', 'nk': 'nk', 'nl': 'nl', 'nn': 'nn', 'nb': 'nb',
'nc': 'nc', 'nd': 'nd', 'nf': 'nf', 'ng': 'ng', 'ny': 'ny', 'np': 'np', 'nr':
'nr', 'ns': 'ns', 'nt': 'nt', 'yc': 'yc', 'fp': 'fp', 'fr': 'fr', 'fs': 'fs',
'ft': 'ft', 'fy': 'fy', 'sl': 'sl', 'yd': 'yd', 'fb': 'fb', 'fc': 'fc', 'fd':
'fd', 'ff': 'ff', 'fg': 'fg', 'fk': 'fk', 'fl': 'fl', 'fn': 'fn', 'kc': 'kc',
'kb': 'kb', 'sy': 'sy', 'kg': 'kg', 'kf': 'kf', 'kd': 'kd', 'kk': 'kk', 'sr':
'sr', 'sp': 'sp', 'kn': 'kn', 'kl': 'kl', 'ks': 'ks', 'kr': 'kr', 'kp': 'kp',
'sn': 'sn', 'kt': 'kt', 'sc': 'sc', 'sb': 'sb', 'ky': 'ky', 'sg': 'sg', 'sf':
'sf', 'sd': 'sd'}, 'b': {'gt': 'gt', 'gs': 'gs', 'gr': 'gr', 'gp': 'gp', 'gy':
'gy', 'gg': 'gg', 'gf': 'gf', 'gd': 'gd', 'gc': 'gc', 'gb': 'gb', 'gn': 'gn',
'gl': 'gl', 'gk': 'gk', 'ys': 'ys', 'lf': 'lf', 'lg': 'lg', 'ld': 'ld', 'yr':
'yr', 'lb': 'lb', 'lc': 'lc', 'ty': 'ty', 'ln': 'ln', 'tt': 'tt', 'tr': 'tr',
'ts': 'ts', 'tp': 'tp', 'yt': 'yt', 'tn': 'tn', 'tl': 'tl', 'lr': 'lr', 'ls':
'ls', 'lp': 'lp', 'tf': 'tf', 'tg': 'tg', 'td': 'td', 'tb': 'tb', 'tc': 'tc',
'ly': 'ly', 'dn': 'dn', 'dl': 'dl', 'dk': 'dk', 'yn': 'yn', 'df': 'df', 'dg':
'dg', 'dd': 'dd', 'yb': 'yb', 'db': 'db', 'dc': 'dc', 'yg': 'yg', 'yf': 'yf',
'yy': 'yy', 'dy': 'dy', 'yp': 'yp', 'dt': 'dt', 'cd': 'cd', 'dr': 'dr', 'ds':
'ds', 'dp': 'dp', 'rt': 'rt', 'rp': 'rp', 'rr': 'rr', 'rs': 'rs', 'ry': 'ry',
'rd': 'rd', 'rf': 'rf', 'rg': 'rg', 'rb': 'rb', 'rc': 'rc', 'rl': 'rl', 'rn':
'rn', 'rk': 'rk', 'bd': 'bd', 'bf': 'bf', 'bg': 'bg', 'bb': 'bb', 'bc': 'bc',
'bl': 'bl', 'bn': 'bn', 'bk': 'bk', 'bt': 'bt', 'bp': 'bp', 'br': 'br', 'bs':
'bs', 'by': 'by', 'll': 'll', 'ck': 'ck', 'cn': 'cn', 'cl': 'cl', 'cc': 'cc',
'cb': 'cb', 'cg': 'cg', 'cf': 'cf', 'lk': 'lk', 'cy': 'cy', 'cs': 'cs', 'cr':
'cr', 'cp': 'cp', 'ct': 'ct', 'pr': 'pr', 'ps': 'ps', 'pp': 'pp', 'pt': 'pt',
'py': 'py', 'lt': 'lt', 'pb': 'pb', 'pc': 'pc', 'pf': 'pf', 'pg': 'pg', 'pd':
'pd', 'pk': 'pk', 'pn': 'pn', 'pl': 'pl', 'tk': 'tk', 'ss': 'ss', 'yk': 'yk',
'st': 'st', 'yl': 'yl', 'sk': 'sk', 'nk': 'nk', 'nl': 'nl', 'nn': 'nn', 'nb':
'nb', 'nc': 'nc', 'nd': 'nd', 'nf': 'nf', 'ng': 'ng', 'ny': 'ny', 'np': 'np',
'nr': 'nr', 'ns': 'ns', 'nt': 'nt', 'yc': 'yc', 'fp': 'fp', 'fr': 'fr', 'fs':
'fs', 'ft': 'ft', 'fy': 'fy', 'sl': 'sl', 'yd': 'yd', 'fb': 'fb', 'fc': 'fc',
'fd': 'fd', 'ff': 'ff', 'fg': 'fg', 'fk': 'fk', 'fl': 'fl', 'fn': 'fn', 'kc':
'kc', 'kb': 'kb', 'sy': 'sy', 'kg': 'kg', 'kf': 'kf', 'kd': 'kd', 'kk': 'kk',
'sr': 'sr', 'sp': 'sp', 'kn': 'kn', 'kl': 'kl', 'ks': 'ks', 'kr': 'kr', 'kp':
'kp', 'sn': 'sn', 'kt': 'kt', 'sc': 'sc', 'sb': 'sb', 'ky': 'ky', 'sg': 'sg',
'sf': 'sf', 'sd': 'sd'}, 'd': {'gt': 'gt', 'gs': 'gs', 'gr': 'gr', 'gp': 'gp',
'gy': 'gy', 'gg': 'gg', 'gf': 'gf', 'gd': 'gd', 'gc': 'gc', 'gb': 'gb', 'gn':
'gn', 'gl': 'gl', 'gk': 'gk', 'ys': 'ys', 'lf': 'lf', 'lg': 'lg', 'ld': 'ld',
'yr': 'yr', 'lb': 'lb', 'lc': 'lc', 'ty': 'ty', 'ln': 'ln', 'tt': 'tt', 'tr':
'tr', 'ts': 'ts', 'tp': 'tp', 'yt': 'yt', 'tn': 'tn', 'tl': 'tl', 'lr': 'lr',
'ls': 'ls', 'lp': 'lp', 'tf': 'tf', 'tg': 'tg', 'td': 'td', 'tb': 'tb', 'tc':
'tc', 'ly': 'ly', 'dn': 'dn', 'dl': 'dl', 'dk': 'dk', 'yn': 'yn', 'df': 'df',
'dg': 'dg', 'dd': 'dd', 'yb': 'yb', 'db': 'db', 'dc': 'dc', 'yg': 'yg', 'yf':
'yf', 'yy': 'yy', 'dy': 'dy', 'yp': 'yp', 'dt': 'dt', 'cd': 'cd', 'dr': 'dr',
'ds': 'ds', 'dp': 'dp', 'rt': 'rt', 'rp': 'rp', 'rr': 'rr', 'rs': 'rs', 'ry':
'ry', 'rd': 'rd', 'rf': 'rf', 'rg': 'rg', 'rb': 'rb', 'rc': 'rc', 'rl': 'rl',
'rn': 'rn', 'rk': 'rk', 'bd': 'bd', 'bf': 'bf', 'bg': 'bg', 'bb': 'bb', 'bc':
'bc', 'bl': 'bl', 'bn': 'bn', 'bk': 'bk', 'bt': 'bt', 'bp': 'bp', 'br': 'br',
'bs': 'bs', 'by': 'by', 'll': 'll', 'ck': 'ck', 'cn': 'cn', 'cl': 'cl', 'cc':
'cc', 'cb': 'cb', 'cg': 'cg', 'cf': 'cf', 'lk': 'lk', 'cy': 'cy', 'cs': 'cs',
'cr': 'cr', 'cp': 'cp', 'ct': 'ct', 'pr': 'pr', 'ps': 'ps', 'pp': 'pp', 'pt':
'pt', 'py': 'py', 'lt': 'lt', 'pb': 'pb', 'pc': 'pc', 'pf': 'pf', 'pg': 'pg',
'pd': 'pd', 'pk': 'pk', 'pn': 'pn', 'pl': 'pl', 'tk': 'tk', 'ss': 'ss', 'yk':
'yk', 'st': 'st', 'yl': 'yl', 'sk': 'sk', 'nk': 'nk', 'nl': 'nl', 'nn': 'nn',
'nb': 'nb', 'nc': 'nc', 'nd': 'nd', 'nf': 'nf', 'ng': 'ng', 'ny': 'ny', 'np':
'np', 'nr': 'nr', 'ns': 'ns', 'nt': 'nt', 'yc': 'yc', 'fp': 'fp', 'fr': 'fr',
'fs': 'fs', 'ft': 'ft', 'fy': 'fy', 'sl': 'sl', 'yd': 'yd', 'fb': 'fb', 'fc':
'fc', 'fd': 'fd', 'ff': 'ff', 'fg': 'fg', 'fk': 'fk', 'fl': 'fl', 'fn': 'fn',
'kc': 'kc', 'kb': 'kb', 'sy': 'sy', 'kg': 'kg', 'kf': 'kf', 'kd': 'kd', 'kk':
'kk', 'sr': 'sr', 'sp': 'sp', 'kn': 'kn', 'kl': 'kl', 'ks': 'ks', 'kr': 'kr',
'kp': 'kp', 'sn': 'sn', 'kt': 'kt', 'sc': 'sc', 'sb': 'sb', 'ky': 'ky', 'sg':
'sg', 'sf': 'sf', 'sd': 'sd'}, 'g': {'gt': 'gt', 'gs': 'gs', 'gr': 'gr', 'gp':
'gp', 'gy': 'gy', 'gg': 'gg', 'gf': 'gf', 'gd': 'gd', 'gc': 'gc', 'gb': 'gb',
'gn': 'gn', 'gl': 'gl', 'gk': 'gk', 'ys': 'ys', 'lf': 'lf', 'lg': 'lg', 'ld':
'ld', 'yr': 'yr', 'lb': 'lb', 'lc': 'lc', 'ty': 'ty', 'ln': 'ln', 'tt': 'tt',
'tr': 'tr', 'ts': 'ts', 'tp': 'tp', 'yt': 'yt', 'tn': 'tn', 'tl': 'tl', 'lr':
'lr', 'ls': 'ls', 'lp': 'lp', 'tf': 'tf', 'tg': 'tg', 'td': 'td', 'tb': 'tb',
'tc': 'tc', 'ly': 'ly', 'dn': 'dn', 'dl': 'dl', 'dk': 'dk', 'yn': 'yn', 'df':
'df', 'dg': 'dg', 'dd': 'dd', 'yb': 'yb', 'db': 'db', 'dc': 'dc', 'yg': 'yg',
'yf': 'yf', 'yy': 'yy', 'dy': 'dy', 'yp': 'yp', 'dt': 'dt', 'cd': 'cd', 'dr':
'dr', 'ds': 'ds', 'dp': 'dp', 'rt': 'rt', 'rp': 'rp', 'rr': 'rr', 'rs': 'rs',
'ry': 'ry', 'rd': 'rd', 'rf': 'rf', 'rg': 'rg', 'rb': 'rb', 'rc': 'rc', 'rl':
'rl', 'rn': 'rn', 'rk': 'rk', 'bd': 'bd', 'bf': 'bf', 'bg': 'bg', 'bb': 'bb',
'bc': 'bc', 'bl': 'bl', 'bn': 'bn', 'bk': 'bk', 'bt': 'bt', 'bp': 'bp', 'br':
'br', 'bs': 'bs', 'by': 'by', 'll': 'll', 'ck': 'ck', 'cn': 'cn', 'cl': 'cl',
'cc': 'cc', 'cb': 'cb', 'cg': 'cg', 'cf': 'cf', 'lk': 'lk', 'cy': 'cy', 'cs':
'cs', 'cr': 'cr', 'cp': 'cp', 'ct': 'ct', 'pr': 'pr', 'ps': 'ps', 'pp': 'pp',
'pt': 'pt', 'py': 'py', 'lt': 'lt', 'pb': 'pb', 'pc': 'pc', 'pf': 'pf', 'pg':
'pg', 'pd': 'pd', 'pk': 'pk', 'pn': 'pn', 'pl': 'pl', 'tk': 'tk', 'ss': 'ss',
'yk': 'yk', 'st': 'st', 'yl': 'yl', 'sk': 'sk', 'nk': 'nk', 'nl': 'nl', 'nn':
'nn', 'nb': 'nb', 'nc': 'nc', 'nd': 'nd', 'nf': 'nf', 'ng': 'ng', 'ny': 'ny',
'np': 'np', 'nr': 'nr', 'ns': 'ns', 'nt': 'nt', 'yc': 'yc', 'fp': 'fp', 'fr':
'fr', 'fs': 'fs', 'ft': 'ft', 'fy': 'fy', 'sl': 'sl', 'yd': 'yd', 'fb': 'fb',
'fc': 'fc', 'fd': 'fd', 'ff': 'ff', 'fg': 'fg', 'fk': 'fk', 'fl': 'fl', 'fn':
'fn', 'kc': 'kc', 'kb': 'kb', 'sy': 'sy', 'kg': 'kg', 'kf': 'kf', 'kd': 'kd',
'kk': 'kk', 'sr': 'sr', 'sp': 'sp', 'kn': 'kn', 'kl': 'kl', 'ks': 'ks', 'kr':
'kr', 'kp': 'kp', 'sn': 'sn', 'kt': 'kt', 'sc': 'sc', 'sb': 'sb', 'ky': 'ky',
'sg': 'sg', 'sf': 'sf', 'sd': 'sd'}, 'f': {'gt': 'gt', 'gs': 'gs', 'gr': 'gr',
'gp': 'gp', 'gy': 'gy', 'gg': 'gg', 'gf': 'gf', 'gd': 'gd', 'gc': 'gc', 'gb':
'gb', 'gn': 'gn', 'gl': 'gl', 'gk': 'gk', 'ys': 'ys', 'lf': 'lf', 'lg': 'lg',
'ld': 'ld', 'yr': 'yr', 'lb': 'lb', 'lc': 'lc', 'ty': 'ty', 'ln': 'ln', 'tt':
'tt', 'tr': 'tr', 'ts': 'ts', 'tp': 'tp', 'yt': 'yt', 'tn': 'tn', 'tl': 'tl',
'lr': 'lr', 'ls': 'ls', 'lp': 'lp', 'tf': 'tf', 'tg': 'tg', 'td': 'td', 'tb':
'tb', 'tc': 'tc', 'ly': 'ly', 'dn': 'dn', 'dl': 'dl', 'dk': 'dk', 'yn': 'yn',
'df': 'df', 'dg': 'dg', 'dd': 'dd', 'yb': 'yb', 'db': 'db', 'dc': 'dc', 'yg':
'yg', 'yf': 'yf', 'yy': 'yy', 'dy': 'dy', 'yp': 'yp', 'dt': 'dt', 'cd': 'cd',
'dr': 'dr', 'ds': 'ds', 'dp': 'dp', 'rt': 'rt', 'rp': 'rp', 'rr': 'rr', 'rs':
'rs', 'ry': 'ry', 'rd': 'rd', 'rf': 'rf', 'rg': 'rg', 'rb': 'rb', 'rc': 'rc',
'rl': 'rl', 'rn': 'rn', 'rk': 'rk', 'bd': 'bd', 'bf': 'bf', 'bg': 'bg', 'bb':
'bb', 'bc': 'bc', 'bl': 'bl', 'bn': 'bn', 'bk': 'bk', 'bt': 'bt', 'bp': 'bp',
'br': 'br', 'bs': 'bs', 'by': 'by', 'll': 'll', 'ck': 'ck', 'cn': 'cn', 'cl':
'cl', 'cc': 'cc', 'cb': 'cb', 'cg': 'cg', 'cf': 'cf', 'lk': 'lk', 'cy': 'cy',
'cs': 'cs', 'cr': 'cr', 'cp': 'cp', 'ct': 'ct', 'pr': 'pr', 'ps': 'ps', 'pp':
'pp', 'pt': 'pt', 'py': 'py', 'lt': 'lt', 'pb': 'pb', 'pc': 'pc', 'pf': 'pf',
'pg': 'pg', 'pd': 'pd', 'pk': 'pk', 'pn': 'pn', 'pl': 'pl', 'tk': 'tk', 'ss':
'ss', 'yk': 'yk', 'st': 'st', 'yl': 'yl', 'sk': 'sk', 'nk': 'nk', 'nl': 'nl',
'nn': 'nn', 'nb': 'nb', 'nc': 'nc', 'nd': 'nd', 'nf': 'nf', 'ng': 'ng', 'ny':
'ny', 'np': 'np', 'nr': 'nr', 'ns': 'ns', 'nt': 'nt', 'yc': 'yc', 'fp': 'fp',
'fr': 'fr', 'fs': 'fs', 'ft': 'ft', 'fy': 'fy', 'sl': 'sl', 'yd': 'yd', 'fb':
'fb', 'fc': 'fc', 'fd': 'fd', 'ff': 'ff', 'fg': 'fg', 'fk': 'fk', 'fl': 'fl',
'fn': 'fn', 'kc': 'kc', 'kb': 'kb', 'sy': 'sy', 'kg': 'kg', 'kf': 'kf', 'kd':
'kd', 'kk': 'kk', 'sr': 'sr', 'sp': 'sp', 'kn': 'kn', 'kl': 'kl', 'ks': 'ks',
'kr': 'kr', 'kp': 'kp', 'sn': 'sn', 'kt': 'kt', 'sc': 'sc', 'sb': 'sb', 'ky':
'ky', 'sg': 'sg', 'sf': 'sf', 'sd': 'sd'}, 'k': {'gt': 'gt', 'gs': 'gs', 'gr':
'gr', 'gp': 'gp', 'gy': 'gy', 'gg': 'gg', 'gf': 'gf', 'gd': 'gd', 'gc': 'gc',
'gb': 'gb', 'gn': 'gn', 'gl': 'gl', 'gk': 'gk', 'ys': 'ys', 'lf': 'lf', 'lg':
'lg', 'ld': 'ld', 'yr': 'yr', 'lb': 'lb', 'lc': 'lc', 'ty': 'ty', 'ln': 'ln',
'tt': 'tt', 'tr': 'tr', 'ts': 'ts', 'tp': 'tp', 'yt': 'yt', 'tn': 'tn', 'tl':
'tl', 'lr': 'lr', 'ls': 'ls', 'lp': 'lp', 'tf': 'tf', 'tg': 'tg', 'td': 'td',
'tb': 'tb', 'tc': 'tc', 'ly': 'ly', 'dn': 'dn', 'dl': 'dl', 'dk': 'dk', 'yn':
'yn', 'df': 'df', 'dg': 'dg', 'dd': 'dd', 'yb': 'yb', 'db': 'db', 'dc': 'dc',
'yg': 'yg', 'yf': 'yf', 'yy': 'yy', 'dy': 'dy', 'yp': 'yp', 'dt': 'dt', 'cd':
'cd', 'dr': 'dr', 'ds': 'ds', 'dp': 'dp', 'rt': 'rt', 'rp': 'rp', 'rr': 'rr',
'rs': 'rs', 'ry': 'ry', 'rd': 'rd', 'rf': 'rf', 'rg': 'rg', 'rb': 'rb', 'rc':
'rc', 'rl': 'rl', 'rn': 'rn', 'rk': 'rk', 'bd': 'bd', 'bf': 'bf', 'bg': 'bg',
'bb': 'bb', 'bc': 'bc', 'bl': 'bl', 'bn': 'bn', 'bk': 'bk', 'bt': 'bt', 'bp':
'bp', 'br': 'br', 'bs': 'bs', 'by': 'by', 'll': 'll', 'ck': 'ck', 'cn': 'cn',
'cl': 'cl', 'cc': 'cc', 'cb': 'cb', 'cg': 'cg', 'cf': 'cf', 'lk': 'lk', 'cy':
'cy', 'cs': 'cs', 'cr': 'cr', 'cp': 'cp', 'ct': 'ct', 'pr': 'pr', 'ps': 'ps',
'pp': 'pp', 'pt': 'pt', 'py': 'py', 'lt': 'lt', 'pb': 'pb', 'pc': 'pc', 'pf':
'pf', 'pg': 'pg', 'pd': 'pd', 'pk': 'pk', 'pn': 'pn', 'pl': 'pl', 'tk': 'tk',
'ss': 'ss', 'yk': 'yk', 'st': 'st', 'yl': 'yl', 'sk': 'sk', 'nk': 'nk', 'nl':
'nl', 'nn': 'nn', 'nb': 'nb', 'nc': 'nc', 'nd': 'nd', 'nf': 'nf', 'ng': 'ng',
'ny': 'ny', 'np': 'np', 'nr': 'nr', 'ns': 'ns', 'nt': 'nt', 'yc': 'yc', 'fp':
'fp', 'fr': 'fr', 'fs': 'fs', 'ft': 'ft', 'fy': 'fy', 'sl': 'sl', 'yd': 'yd',
'fb': 'fb', 'fc': 'fc', 'fd': 'fd', 'ff': 'ff', 'fg': 'fg', 'fk': 'fk', 'fl':
'fl', 'fn': 'fn', 'kc': 'kc', 'kb': 'kb', 'sy': 'sy', 'kg': 'kg', 'kf': 'kf',
'kd': 'kd', 'kk': 'kk', 'sr': 'sr', 'sp': 'sp', 'kn': 'kn', 'kl': 'kl', 'ks':
'ks', 'kr': 'kr', 'kp': 'kp', 'sn': 'sn', 'kt': 'kt', 'sc': 'sc', 'sb': 'sb',
'ky': 'ky', 'sg': 'sg', 'sf': 'sf', 'sd': 'sd'}, 'l': {'gt': 'gt', 'gs': 'gs',
'gr': 'gr', 'gp': 'gp', 'gy': 'gy', 'gg': 'gg', 'gf': 'gf', 'gd': 'gd', 'gc':
'gc', 'gb': 'gb', 'gn': 'gn', 'gl': 'gl', 'gk': 'gk', 'ys': 'ys', 'lf': 'lf',
'lg': 'lg', 'ld': 'ld', 'yr': 'yr', 'lb': 'lb', 'lc': 'lc', 'ty': 'ty', 'ln':
'ln', 'tt': 'tt', 'tr': 'tr', 'ts': 'ts', 'tp': 'tp', 'yt': 'yt', 'tn': 'tn',
'tl': 'tl', 'lr': 'lr', 'ls': 'ls', 'lp': 'lp', 'tf': 'tf', 'tg': 'tg', 'td':
'td', 'tb': 'tb', 'tc': 'tc', 'ly': 'ly', 'dn': 'dn', 'dl': 'dl', 'dk': 'dk',
'yn': 'yn', 'df': 'df', 'dg': 'dg', 'dd': 'dd', 'yb': 'yb', 'db': 'db', 'dc':
'dc', 'yg': 'yg', 'yf': 'yf', 'yy': 'yy', 'dy': 'dy', 'yp': 'yp', 'dt': 'dt',
'cd': 'cd', 'dr': 'dr', 'ds': 'ds', 'dp': 'dp', 'rt': 'rt', 'rp': 'rp', 'rr':
'rr', 'rs': 'rs', 'ry': 'ry', 'rd': 'rd', 'rf': 'rf', 'rg': 'rg', 'rb': 'rb',
'rc': 'rc', 'rl': 'rl', 'rn': 'rn', 'rk': 'rk', 'bd': 'bd', 'bf': 'bf', 'bg':
'bg', 'bb': 'bb', 'bc': 'bc', 'bl': 'bl', 'bn': 'bn', 'bk': 'bk', 'bt': 'bt',
'bp': 'bp', 'br': 'br', 'bs': 'bs', 'by': 'by', 'll': 'll', 'ck': 'ck', 'cn':
'cn', 'cl': 'cl', 'cc': 'cc', 'cb': 'cb', 'cg': 'cg', 'cf': 'cf', 'lk': 'lk',
'cy': 'cy', 'cs': 'cs', 'cr': 'cr', 'cp': 'cp', 'ct': 'ct', 'pr': 'pr', 'ps':
'ps', 'pp': 'pp', 'pt': 'pt', 'py': 'py', 'lt': 'lt', 'pb': 'pb', 'pc': 'pc',
'pf': 'pf', 'pg': 'pg', 'pd': 'pd', 'pk': 'pk', 'pn': 'pn', 'pl': 'pl', 'tk':
'tk', 'ss': 'ss', 'yk': 'yk', 'st': 'st', 'yl': 'yl', 'sk': 'sk', 'nk': 'nk',
'nl': 'nl', 'nn': 'nn', 'nb': 'nb', 'nc': 'nc', 'nd': 'nd', 'nf': 'nf', 'ng':
'ng', 'ny': 'ny', 'np': 'np', 'nr': 'nr', 'ns': 'ns', 'nt': 'nt', 'yc': 'yc',
'fp': 'fp', 'fr': 'fr', 'fs': 'fs', 'ft': 'ft', 'fy': 'fy', 'sl': 'sl', 'yd':
'yd', 'fb': 'fb', 'fc': 'fc', 'fd': 'fd', 'ff': 'ff', 'fg': 'fg', 'fk': 'fk',
'fl': 'fl', 'fn': 'fn', 'kc': 'kc', 'kb': 'kb', 'sy': 'sy', 'kg': 'kg', 'kf':
'kf', 'kd': 'kd', 'kk': 'kk', 'sr': 'sr', 'sp': 'sp', 'kn': 'kn', 'kl': 'kl',
'ks': 'ks', 'kr': 'kr', 'kp': 'kp', 'sn': 'sn', 'kt': 'kt', 'sc': 'sc', 'sb':
'sb', 'ky': 'ky', 'sg': 'sg', 'sf': 'sf', 'sd': 'sd'}, 'n': {'gt': 'gt', 'gs':
'gs', 'gr': 'gr', 'gp': 'gp', 'gy': 'gy', 'gg': 'gg', 'gf': 'gf', 'gd': 'gd',
'gc': 'gc', 'gb': 'gb', 'gn': 'gn', 'gl': 'gl', 'gk': 'gk', 'ys': 'ys', 'lf':
'lf', 'lg': 'lg', 'ld': 'ld', 'yr': 'yr', 'lb': 'lb', 'lc': 'lc', 'ty': 'ty',
'ln': 'ln', 'tt': 'tt', 'tr': 'tr', 'ts': 'ts', 'tp': 'tp', 'yt': 'yt', 'tn':
'tn', 'tl': 'tl', 'lr': 'lr', 'ls': 'ls', 'lp': 'lp', 'tf': 'tf', 'tg': 'tg',
'td': 'td', 'tb': 'tb', 'tc': 'tc', 'ly': 'ly', 'dn': 'dn', 'dl': 'dl', 'dk':
'dk', 'yn': 'yn', 'df': 'df', 'dg': 'dg', 'dd': 'dd', 'yb': 'yb', 'db': 'db',
'dc': 'dc', 'yg': 'yg', 'yf': 'yf', 'yy': 'yy', 'dy': 'dy', 'yp': 'yp', 'dt':
'dt', 'cd': 'cd', 'dr': 'dr', 'ds': 'ds', 'dp': 'dp', 'rt': 'rt', 'rp': 'rp',
'rr': 'rr', 'rs': 'rs', 'ry': 'ry', 'rd': 'rd', 'rf': 'rf', 'rg': 'rg', 'rb':
'rb', 'rc': 'rc', 'rl': 'rl', 'rn': 'rn', 'rk': 'rk', 'bd': 'bd', 'bf': 'bf',
'bg': 'bg', 'bb': 'bb', 'bc': 'bc', 'bl': 'bl', 'bn': 'bn', 'bk': 'bk', 'bt':
'bt', 'bp': 'bp', 'br': 'br', 'bs': 'bs', 'by': 'by', 'll': 'll', 'ck': 'ck',
'cn': 'cn', 'cl': 'cl', 'cc': 'cc', 'cb': 'cb', 'cg': 'cg', 'cf': 'cf', 'lk':
'lk', 'cy': 'cy', 'cs': 'cs', 'cr': 'cr', 'cp': 'cp', 'ct': 'ct', 'pr': 'pr',
'ps': 'ps', 'pp': 'pp', 'pt': 'pt', 'py': 'py', 'lt': 'lt', 'pb': 'pb', 'pc':
'pc', 'pf': 'pf', 'pg': 'pg', 'pd': 'pd', 'pk': 'pk', 'pn': 'pn', 'pl': 'pl',
'tk': 'tk', 'ss': 'ss', 'yk': 'yk', 'st': 'st', 'yl': 'yl', 'sk': 'sk', 'nk':
'nk', 'nl': 'nl', 'nn': 'nn', 'nb': 'nb', 'nc': 'nc', 'nd': 'nd', 'nf': 'nf',
'ng': 'ng', 'ny': 'ny', 'np': 'np', 'nr': 'nr', 'ns': 'ns', 'nt': 'nt', 'yc':
'yc', 'fp': 'fp', 'fr': 'fr', 'fs': 'fs', 'ft': 'ft', 'fy': 'fy', 'sl': 'sl',
'yd': 'yd', 'fb': 'fb', 'fc': 'fc', 'fd': 'fd', 'ff': 'ff', 'fg': 'fg', 'fk':
'fk', 'fl': 'fl', 'fn': 'fn', 'kc': 'kc', 'kb': 'kb', 'sy': 'sy', 'kg': 'kg',
'kf': 'kf', 'kd': 'kd', 'kk': 'kk', 'sr': 'sr', 'sp': 'sp', 'kn': 'kn', 'kl':
'kl', 'ks': 'ks', 'kr': 'kr', 'kp': 'kp', 'sn': 'sn', 'kt': 'kt', 'sc': 'sc',
'sb': 'sb', 'ky': 'ky', 'sg': 'sg', 'sf': 'sf', 'sd': 'sd'}, 'p': {'gt': 'gt',
'gs': 'gs', 'gr': 'gr', 'gp': 'gp', 'gy': 'gy', 'gg': 'gg', 'gf': 'gf', 'gd':
'gd', 'gc': 'gc', 'gb': 'gb', 'gn': 'gn', 'gl': 'gl', 'gk': 'gk', 'ys': 'ys',
'lf': 'lf', 'lg': 'lg', 'ld': 'ld', 'yr': 'yr', 'lb': 'lb', 'lc': 'lc', 'ty':
'ty', 'ln': 'ln', 'tt': 'tt', 'tr': 'tr', 'ts': 'ts', 'tp': 'tp', 'yt': 'yt',
'tn': 'tn', 'tl': 'tl', 'lr': 'lr', 'ls': 'ls', 'lp': 'lp', 'tf': 'tf', 'tg':
'tg', 'td': 'td', 'tb': 'tb', 'tc': 'tc', 'ly': 'ly', 'dn': 'dn', 'dl': 'dl',
'dk': 'dk', 'yn': 'yn', 'df': 'df', 'dg': 'dg', 'dd': 'dd', 'yb': 'yb', 'db':
'db', 'dc': 'dc', 'yg': 'yg', 'yf': 'yf', 'yy': 'yy', 'dy': 'dy', 'yp': 'yp',
'dt': 'dt', 'cd': 'cd', 'dr': 'dr', 'ds': 'ds', 'dp': 'dp', 'rt': 'rt', 'rp':
'rp', 'rr': 'rr', 'rs': 'rs', 'ry': 'ry', 'rd': 'rd', 'rf': 'rf', 'rg': 'rg',
'rb': 'rb', 'rc': 'rc', 'rl': 'rl', 'rn': 'rn', 'rk': 'rk', 'bd': 'bd', 'bf':
'bf', 'bg': 'bg', 'bb': 'bb', 'bc': 'bc', 'bl': 'bl', 'bn': 'bn', 'bk': 'bk',
'bt': 'bt', 'bp': 'bp', 'br': 'br', 'bs': 'bs', 'by': 'by', 'll': 'll', 'ck':
'ck', 'cn': 'cn', 'cl': 'cl', 'cc': 'cc', 'cb': 'cb', 'cg': 'cg', 'cf': 'cf',
'lk': 'lk', 'cy': 'cy', 'cs': 'cs', 'cr': 'cr', 'cp': 'cp', 'ct': 'ct', 'pr':
'pr', 'ps': 'ps', 'pp': 'pp', 'pt': 'pt', 'py': 'py', 'lt': 'lt', 'pb': 'pb',
'pc': 'pc', 'pf': 'pf', 'pg': 'pg', 'pd': 'pd', 'pk': 'pk', 'pn': 'pn', 'pl':
'pl', 'tk': 'tk', 'ss': 'ss', 'yk': 'yk', 'st': 'st', 'yl': 'yl', 'sk': 'sk',
'nk': 'nk', 'nl': 'nl', 'nn': 'nn', 'nb': 'nb', 'nc': 'nc', 'nd': 'nd', 'nf':
'nf', 'ng': 'ng', 'ny': 'ny', 'np': 'np', 'nr': 'nr', 'ns': 'ns', 'nt': 'nt',
'yc': 'yc', 'fp': 'fp', 'fr': 'fr', 'fs': 'fs', 'ft': 'ft', 'fy': 'fy', 'sl':
'sl', 'yd': 'yd', 'fb': 'fb', 'fc': 'fc', 'fd': 'fd', 'ff': 'ff', 'fg': 'fg',
'fk': 'fk', 'fl': 'fl', 'fn': 'fn', 'kc': 'kc', 'kb': 'kb', 'sy': 'sy', 'kg':
'kg', 'kf': 'kf', 'kd': 'kd', 'kk': 'kk', 'sr': 'sr', 'sp': 'sp', 'kn': 'kn',
'kl': 'kl', 'ks': 'ks', 'kr': 'kr', 'kp': 'kp', 'sn': 'sn', 'kt': 'kt', 'sc':
'sc', 'sb': 'sb', 'ky': 'ky', 'sg': 'sg', 'sf': 'sf', 'sd': 'sd'}, 's': {'gt':
'gt', 'gs': 'gs', 'gr': 'gr', 'gp': 'gp', 'gy': 'gy', 'gg': 'gg', 'gf': 'gf',
'gd': 'gd', 'gc': 'gc', 'gb': 'gb', 'gn': 'gn', 'gl': 'gl', 'gk': 'gk', 'ys':
'ys', 'lf': 'lf', 'lg': 'lg', 'ld': 'ld', 'yr': 'yr', 'lb': 'lb', 'lc': 'lc',
'ty': 'ty', 'ln': 'ln', 'tt': 'tt', 'tr': 'tr', 'ts': 'ts', 'tp': 'tp', 'yt':
'yt', 'tn': 'tn', 'tl': 'tl', 'lr': 'lr', 'ls': 'ls', 'lp': 'lp', 'tf': 'tf',
'tg': 'tg', 'td': 'td', 'tb': 'tb', 'tc': 'tc', 'ly': 'ly', 'dn': 'dn', 'dl':
'dl', 'dk': 'dk', 'yn': 'yn', 'df': 'df', 'dg': 'dg', 'dd': 'dd', 'yb': 'yb',
'db': 'db', 'dc': 'dc', 'yg': 'yg', 'yf': 'yf', 'yy': 'yy', 'dy': 'dy', 'yp':
'yp', 'dt': 'dt', 'cd': 'cd', 'dr': 'dr', 'ds': 'ds', 'dp': 'dp', 'rt': 'rt',
'rp': 'rp', 'rr': 'rr', 'rs': 'rs', 'ry': 'ry', 'rd': 'rd', 'rf': 'rf', 'rg':
'rg', 'rb': 'rb', 'rc': 'rc', 'rl': 'rl', 'rn': 'rn', 'rk': 'rk', 'bd': 'bd',
'bf': 'bf', 'bg': 'bg', 'bb': 'bb', 'bc': 'bc', 'bl': 'bl', 'bn': 'bn', 'bk':
'bk', 'bt': 'bt', 'bp': 'bp', 'br': 'br', 'bs': 'bs', 'by': 'by', 'll': 'll',
'ck': 'ck', 'cn': 'cn', 'cl': 'cl', 'cc': 'cc', 'cb': 'cb', 'cg': 'cg', 'cf':
'cf', 'lk': 'lk', 'cy': 'cy', 'cs': 'cs', 'cr': 'cr', 'cp': 'cp', 'ct': 'ct',
'pr': 'pr', 'ps': 'ps', 'pp': 'pp', 'pt': 'pt', 'py': 'py', 'lt': 'lt', 'pb':
'pb', 'pc': 'pc', 'pf': 'pf', 'pg': 'pg', 'pd': 'pd', 'pk': 'pk', 'pn': 'pn',
'pl': 'pl', 'tk': 'tk', 'ss': 'ss', 'yk': 'yk', 'st': 'st', 'yl': 'yl', 'sk':
'sk', 'nk': 'nk', 'nl': 'nl', 'nn': 'nn', 'nb': 'nb', 'nc': 'nc', 'nd': 'nd',
'nf': 'nf', 'ng': 'ng', 'ny': 'ny', 'np': 'np', 'nr': 'nr', 'ns': 'ns', 'nt':
'nt', 'yc': 'yc', 'fp': 'fp', 'fr': 'fr', 'fs': 'fs', 'ft': 'ft', 'fy': 'fy',
'sl': 'sl', 'yd': 'yd', 'fb': 'fb', 'fc': 'fc', 'fd': 'fd', 'ff': 'ff', 'fg':
'fg', 'fk': 'fk', 'fl': 'fl', 'fn': 'fn', 'kc': 'kc', 'kb': 'kb', 'sy': 'sy',
'kg': 'kg', 'kf': 'kf', 'kd': 'kd', 'kk': 'kk', 'sr': 'sr', 'sp': 'sp', 'kn':
'kn', 'kl': 'kl', 'ks': 'ks', 'kr': 'kr', 'kp': 'kp', 'sn': 'sn', 'kt': 'kt',
'sc': 'sc', 'sb': 'sb', 'ky': 'ky', 'sg': 'sg', 'sf': 'sf', 'sd': 'sd'}, 'r':
{'gt': 'gt', 'gs': 'gs', 'gr': 'gr', 'gp': 'gp', 'gy': 'gy', 'gg': 'gg', 'gf':
'gf', 'gd': 'gd', 'gc': 'gc', 'gb': 'gb', 'gn': 'gn', 'gl': 'gl', 'gk': 'gk',
'ys': 'ys', 'lf': 'lf', 'lg': 'lg', 'ld': 'ld', 'yr': 'yr', 'lb': 'lb', 'lc':
'lc', 'ty': 'ty', 'ln': 'ln', 'tt': 'tt', 'tr': 'tr', 'ts': 'ts', 'tp': 'tp',
'yt': 'yt', 'tn': 'tn', 'tl': 'tl', 'lr': 'lr', 'ls': 'ls', 'lp': 'lp', 'tf':
'tf', 'tg': 'tg', 'td': 'td', 'tb': 'tb', 'tc': 'tc', 'ly': 'ly', 'dn': 'dn',
'dl': 'dl', 'dk': 'dk', 'yn': 'yn', 'df': 'df', 'dg': 'dg', 'dd': 'dd', 'yb':
'yb', 'db': 'db', 'dc': 'dc', 'yg': 'yg', 'yf': 'yf', 'yy': 'yy', 'dy': 'dy',
'yp': 'yp', 'dt': 'dt', 'cd': 'cd', 'dr': 'dr', 'ds': 'ds', 'dp': 'dp', 'rt':
'rt', 'rp': 'rp', 'rr': 'rr', 'rs': 'rs', 'ry': 'ry', 'rd': 'rd', 'rf': 'rf',
'rg': 'rg', 'rb': 'rb', 'rc': 'rc', 'rl': 'rl', 'rn': 'rn', 'rk': 'rk', 'bd':
'bd', 'bf': 'bf', 'bg': 'bg', 'bb': 'bb', 'bc': 'bc', 'bl': 'bl', 'bn': 'bn',
'bk': 'bk', 'bt': 'bt', 'bp': 'bp', 'br': 'br', 'bs': 'bs', 'by': 'by', 'll':
'll', 'ck': 'ck', 'cn': 'cn', 'cl': 'cl', 'cc': 'cc', 'cb': 'cb', 'cg': 'cg',
'cf': 'cf', 'lk': 'lk', 'cy': 'cy', 'cs': 'cs', 'cr': 'cr', 'cp': 'cp', 'ct':
'ct', 'pr': 'pr', 'ps': 'ps', 'pp': 'pp', 'pt': 'pt', 'py': 'py', 'lt': 'lt',
'pb': 'pb', 'pc': 'pc', 'pf': 'pf', 'pg': 'pg', 'pd': 'pd', 'pk': 'pk', 'pn':
'pn', 'pl': 'pl', 'tk': 'tk', 'ss': 'ss', 'yk': 'yk', 'st': 'st', 'yl': 'yl',
'sk': 'sk', 'nk': 'nk', 'nl': 'nl', 'nn': 'nn', 'nb': 'nb', 'nc': 'nc', 'nd':
'nd', 'nf': 'nf', 'ng': 'ng', 'ny': 'ny', 'np': 'np', 'nr': 'nr', 'ns': 'ns',
'nt': 'nt', 'yc': 'yc', 'fp': 'fp', 'fr': 'fr', 'fs': 'fs', 'ft': 'ft', 'fy':
'fy', 'sl': 'sl', 'yd': 'yd', 'fb': 'fb', 'fc': 'fc', 'fd': 'fd', 'ff': 'ff',
'fg': 'fg', 'fk': 'fk', 'fl': 'fl', 'fn': 'fn', 'kc': 'kc', 'kb': 'kb', 'sy':
'sy', 'kg': 'kg', 'kf': 'kf', 'kd': 'kd', 'kk': 'kk', 'sr': 'sr', 'sp': 'sp',
'kn': 'kn', 'kl': 'kl', 'ks': 'ks', 'kr': 'kr', 'kp': 'kp', 'sn': 'sn', 'kt':
'kt', 'sc': 'sc', 'sb': 'sb', 'ky': 'ky', 'sg': 'sg', 'sf': 'sf', 'sd': 'sd'},
't': {'gt': 'gt', 'gs': 'gs', 'gr': 'gr', 'gp': 'gp', 'gy': 'gy', 'gg': 'gg',
'gf': 'gf', 'gd': 'gd', 'gc': 'gc', 'gb': 'gb', 'gn': 'gn', 'gl': 'gl', 'gk':
'gk', 'ys': 'ys', 'lf': 'lf', 'lg': 'lg', 'ld': 'ld', 'yr': 'yr', 'lb': 'lb',
'lc': 'lc', 'ty': 'ty', 'ln': 'ln', 'tt': 'tt', 'tr': 'tr', 'ts': 'ts', 'tp':
'tp', 'yt': 'yt', 'tn': 'tn', 'tl': 'tl', 'lr': 'lr', 'ls': 'ls', 'lp': 'lp',
'tf': 'tf', 'tg': 'tg', 'td': 'td', 'tb': 'tb', 'tc': 'tc', 'ly': 'ly', 'dn':
'dn', 'dl': 'dl', 'dk': 'dk', 'yn': 'yn', 'df': 'df', 'dg': 'dg', 'dd': 'dd',
'yb': 'yb', 'db': 'db', 'dc': 'dc', 'yg': 'yg', 'yf': 'yf', 'yy': 'yy', 'dy':
'dy', 'yp': 'yp', 'dt': 'dt', 'cd': 'cd', 'dr': 'dr', 'ds': 'ds', 'dp': 'dp',
'rt': 'rt', 'rp': 'rp', 'rr': 'rr', 'rs': 'rs', 'ry': 'ry', 'rd': 'rd', 'rf':
'rf', 'rg': 'rg', 'rb': 'rb', 'rc': 'rc', 'rl': 'rl', 'rn': 'rn', 'rk': 'rk',
'bd': 'bd', 'bf': 'bf', 'bg': 'bg', 'bb': 'bb', 'bc': 'bc', 'bl': 'bl', 'bn':
'bn', 'bk': 'bk', 'bt': 'bt', 'bp': 'bp', 'br': 'br', 'bs': 'bs', 'by': 'by',
'll': 'll', 'ck': 'ck', 'cn': 'cn', 'cl': 'cl', 'cc': 'cc', 'cb': 'cb', 'cg':
'cg', 'cf': 'cf', 'lk': 'lk', 'cy': 'cy', 'cs': 'cs', 'cr': 'cr', 'cp': 'cp',
'ct': 'ct', 'pr': 'pr', 'ps': 'ps', 'pp': 'pp', 'pt': 'pt', 'py': 'py', 'lt':
'lt', 'pb': 'pb', 'pc': 'pc', 'pf': 'pf', 'pg': 'pg', 'pd': 'pd', 'pk': 'pk',
'pn': 'pn', 'pl': 'pl', 'tk': 'tk', 'ss': 'ss', 'yk': 'yk', 'st': 'st', 'yl':
'yl', 'sk': 'sk', 'nk': 'nk', 'nl': 'nl', 'nn': 'nn', 'nb': 'nb', 'nc': 'nc',
'nd': 'nd', 'nf': 'nf', 'ng': 'ng', 'ny': 'ny', 'np': 'np', 'nr': 'nr', 'ns':
'ns', 'nt': 'nt', 'yc': 'yc', 'fp': 'fp', 'fr': 'fr', 'fs': 'fs', 'ft': 'ft',
'fy': 'fy', 'sl': 'sl', 'yd': 'yd', 'fb': 'fb', 'fc': 'fc', 'fd': 'fd', 'ff':
'ff', 'fg': 'fg', 'fk': 'fk', 'fl': 'fl', 'fn': 'fn', 'kc': 'kc', 'kb': 'kb',
'sy': 'sy', 'kg': 'kg', 'kf': 'kf', 'kd': 'kd', 'kk': 'kk', 'sr': 'sr', 'sp':
'sp', 'kn': 'kn', 'kl': 'kl', 'ks': 'ks', 'kr': 'kr', 'kp': 'kp', 'sn': 'sn',
'kt': 'kt', 'sc': 'sc', 'sb': 'sb', 'ky': 'ky', 'sg': 'sg', 'sf': 'sf', 'sd':
'sd'}, 'y': {'gt': 'gt', 'gs': 'gs', 'gr': 'gr', 'gp': 'gp', 'gy': 'gy', 'gg':
'gg', 'gf': 'gf', 'gd': 'gd', 'gc': 'gc', 'gb': 'gb', 'gn': 'gn', 'gl': 'gl',
'gk': 'gk', 'ys': 'ys', 'lf': 'lf', 'lg': 'lg', 'ld': 'ld', 'yr': 'yr', 'lb':
'lb', 'lc': 'lc', 'ty': 'ty', 'ln': 'ln', 'tt': 'tt', 'tr': 'tr', 'ts': 'ts',
'tp': 'tp', 'yt': 'yt', 'tn': 'tn', 'tl': 'tl', 'lr': 'lr', 'ls': 'ls', 'lp':
'lp', 'tf': 'tf', 'tg': 'tg', 'td': 'td', 'tb': 'tb', 'tc': 'tc', 'ly': 'ly',
'dn': 'dn', 'dl': 'dl', 'dk': 'dk', 'yn': 'yn', 'df': 'df', 'dg': 'dg', 'dd':
'dd', 'yb': 'yb', 'db': 'db', 'dc': 'dc', 'yg': 'yg', 'yf': 'yf', 'yy': 'yy',
'dy': 'dy', 'yp': 'yp', 'dt': 'dt', 'cd': 'cd', 'dr': 'dr', 'ds': 'ds', 'dp':
'dp', 'rt': 'rt', 'rp': 'rp', 'rr': 'rr', 'rs': 'rs', 'ry': 'ry', 'rd': 'rd',
'rf': 'rf', 'rg': 'rg', 'rb': 'rb', 'rc': 'rc', 'rl': 'rl', 'rn': 'rn', 'rk':
'rk', 'bd': 'bd', 'bf': 'bf', 'bg': 'bg', 'bb': 'bb', 'bc': 'bc', 'bl': 'bl',
'bn': 'bn', 'bk': 'bk', 'bt': 'bt', 'bp': 'bp', 'br': 'br', 'bs': 'bs', 'by':
'by', 'll': 'll', 'ck': 'ck', 'cn': 'cn', 'cl': 'cl', 'cc': 'cc', 'cb': 'cb',
'cg': 'cg', 'cf': 'cf', 'lk': 'lk', 'cy': 'cy', 'cs': 'cs', 'cr': 'cr', 'cp':
'cp', 'ct': 'ct', 'pr': 'pr', 'ps': 'ps', 'pp': 'pp', 'pt': 'pt', 'py': 'py',
'lt': 'lt', 'pb': 'pb', 'pc': 'pc', 'pf': 'pf', 'pg': 'pg', 'pd': 'pd', 'pk':
'pk', 'pn': 'pn', 'pl': 'pl', 'tk': 'tk', 'ss': 'ss', 'yk': 'yk', 'st': 'st',
'yl': 'yl', 'sk': 'sk', 'nk': 'nk', 'nl': 'nl', 'nn': 'nn', 'nb': 'nb', 'nc':
'nc', 'nd': 'nd', 'nf': 'nf', 'ng': 'ng', 'ny': 'ny', 'np': 'np', 'nr': 'nr',
'ns': 'ns', 'nt': 'nt', 'yc': 'yc', 'fp': 'fp', 'fr': 'fr', 'fs': 'fs', 'ft':
'ft', 'fy': 'fy', 'sl': 'sl', 'yd': 'yd', 'fb': 'fb', 'fc': 'fc', 'fd': 'fd',
'ff': 'ff', 'fg': 'fg', 'fk': 'fk', 'fl': 'fl', 'fn': 'fn', 'kc': 'kc', 'kb':
'kb', 'sy': 'sy', 'kg': 'kg', 'kf': 'kf', 'kd': 'kd', 'kk': 'kk', 'sr': 'sr',
'sp': 'sp', 'kn': 'kn', 'kl': 'kl', 'ks': 'ks', 'kr': 'kr', 'kp': 'kp', 'sn':
'sn', 'kt': 'kt', 'sc': 'sc', 'sb': 'sb', 'ky': 'ky', 'sg': 'sg', 'sf': 'sf',
'sd': 'sd'}}
